name: CI

on:
  push:
    branches:
      - "**"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Create two files
        run: |
          touch a.txt
          touch b.dat
          touch c.dat
      - name: Upload files to an artifact - hardcoded names
        uses: actions/upload-artifact@v3
        with:
          name: hardcoded
          path: |
            *.txt
            *.dat
      - name: Store patterns as GITHUB_OUTPUT - separated by newline
        id: upload_pattern_1
        run: |
          UPLOAD_PATTERN_ARRAY=('*.txt' '*.dat')
          SEPARATOR="\\n"
          UPLOAD_PATTERN="$(printf "${SEPARATOR/\\/\\\\}%s" "${UPLOAD_PATTERN_ARRAY[@]}")"
          UPLOAD_PATTERN="${UPLOAD_PATTERN:${#SEPARATOR}}"
          echo ${UPLOAD_PATTERN}
          echo "upload_pattern_separator=${SEPARATOR}" >> ${GITHUB_OUTPUT}
          echo "upload_pattern=${UPLOAD_PATTERN}" >> ${GITHUB_OUTPUT}
      - name: Upload files to an artifact - separated by newline
        uses: actions/upload-artifact@v3
        with:
          name: newline
          path: ${{ steps.upload_pattern_1.outputs.upload_pattern }}
